### PR TITLE
Remove immediate flag in Cursor methods

### PR DESCRIPTION
**Pull request by tshemsedinov**
Closes: https://github.com/metarhia/globalstorage/issues/81

### CODE REVIEW

**Comment by lundibundi** [comment]
@tshemsedinov why don't we just remove methods like `map`, `filter`, `select`, `order`, `desc` and some others from MemoryCursor because they are just copies of methods from Cursor now, as MemoryCursor inherits all methods from Cursor?

**Comment by tshemsedinov** [comment]
@lundibundi of course, I changing that step by step:
- unifying all cursors by moving everything different outside of methods and identical signatures
- rename methods, add more methods, fix tests
- remove duplicated methods from Cursor child classes

I'll do than in next commits

**Comment by tshemsedinov** [comment]
@lundibundi now I am oreparing same optimizations for `MongodbCursor` and `FsCursor`

**Comment by tshemsedinov** [comment]
Landed in db19c45, e4657f6 and cfe86d6

**Pull request closed without merging**
